[package]
name = "bootloader"
version = "0.1.0"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2018"

[build-dependencies]
cc = "1"

[dependencies]
byteorder = { version = "1", default-features = false }
arrayvec = { version = "0.5", default-features = false }
softfp = { git = "ssh://git@github.com/nbdd0121/r2vm.git" }
riscv = { git = "ssh://git@github.com/nbdd0121/r2vm.git" }
spin = "0.7"
log = { version = "0.4", default-features = false }
smoltcp = { version = "0.7", default-features = false, features = ["alloc", "ethernet", "socket-tcp", "socket-udp", "proto-ipv4", "proto-ipv6", "async"] }
compiler_builtins_local = { version = "0.1.50", package = "compiler_builtins" }
unwind = { path = "../../unwind", default-features = false, features = ["unwinder", "personality", "fde-static"]}

[profile.release]
opt-level = 2
lto = "thin"
debug = true
panic = "unwind"
